import type { Lesson } from "./curriculum";

// Węzły słownictwa — każdy utrwala gramatykę z sąsiedniego węzła gramatycznego
// i dokłada tematyczny zestaw słówek + kontekst dla tutora Budiego.
export const VOCAB_LESSONS: Lesson[] = [
  {
    id: "a1-v1",
    level: "A1",
    kind: "vocab",
    title: "Codzienne zwroty",
    subtitle: "Powitania, grzeczność, small talk",
    icon: "👋",
    context: {
      key: "everyday",
      label: "Codzienne zwroty",
      brief: "codzienna rozmowa: powitania, przedstawianie się, grzeczność",
    },
    grammar: {
      title: "Zwroty w praktyce (szyk SVO)",
      body: [
        "Powitania zależą od pory dnia: selamat pagi (rano), selamat siang (południe), selamat sore (popołudnie), selamat malam (wieczór).",
        "„Apa kabar?” = jak się masz? Odpowiedź: „Baik-baik saja” (w porządku) — zauważ reduplikację.",
        "Grzeczność: tolong (proszę o coś), terima kasih (dziękuję), maaf (przepraszam), sama-sama (nie ma za co).",
      ],
      examples: [
        { id: "Selamat pagi, apa kabar?", pl: "Dzień dobry, jak się masz?" },
        { id: "Nama saya Miłosz. Saya dari Polandia.", pl: "Nazywam się Miłosz. Jestem z Polski." },
        { id: "Terima kasih banyak!", pl: "Dziękuję bardzo!" },
      ],
    },
    vocab: [
      { id: "selamat pagi", pl: "dzień dobry (rano)" },
      { id: "apa kabar", pl: "jak się masz" },
      { id: "terima kasih", pl: "dziękuję" },
      { id: "maaf", pl: "przepraszam" },
      { id: "tolong", pl: "proszę (o pomoc)" },
      { id: "sampai jumpa", pl: "do zobaczenia" },
      { id: "nama", pl: "imię" },
    ],
    exercises: [
      { kind: "flashcard", id: "a1-v1-f1", front: "apa kabar", back: "jak się masz" },
      { kind: "flashcard", id: "a1-v1-f2", front: "sampai jumpa", back: "do zobaczenia" },
      {
        kind: "match",
        id: "a1-v1-m1",
        pairs: [
          { id: "selamat pagi", pl: "dzień dobry (rano)" },
          { id: "terima kasih", pl: "dziękuję" },
          { id: "maaf", pl: "przepraszam" },
          { id: "tolong", pl: "proszę (o pomoc)" },
        ],
      },
      {
        kind: "builder",
        id: "a1-v1-b1",
        words: ["Nama", "saya", "Budi"],
        solution: "Nama saya Budi",
        pl: "Nazywam się Budi.",
      },
      {
        kind: "choice",
        id: "a1-v1-c1",
        question: "Ktoś mówi „terima kasih”. Co odpowiesz?",
        options: ["Sama-sama", "Apa kabar", "Selamat malam"],
        answer: "Sama-sama",
        explain: "„Sama-sama” = nie ma za co.",
      },
    ],
  },
  {
    id: "a1-v2",
    level: "A1",
    kind: "vocab",
    title: "Jedzenie i restauracja",
    subtitle: "Zamawianie z mau / bisa / sudah",
    icon: "🍜",
    context: {
      key: "food",
      label: "Jedzenie i restauracja",
      brief: "zamawianie jedzenia w warungu: dania, napoje, ostrość, rachunek",
    },
    grammar: {
      title: "Zamawiam = saya mau + rzecz",
      body: [
        "„Saya mau…” (chcę), „Saya bisa…” (mogę), „Saya sudah…” (już) — znaczniki czasu i modalności stoją PRZED czasownikiem.",
        "Przeczenie: „tidak pedas” (nieostre) — tidak przed przymiotnikiem; „bukan teh” (to nie herbata) — bukan przed rzeczownikiem.",
        "Rachunek: „Minta bon” albo „Berapa semuanya?” (ile w sumie?).",
      ],
      examples: [
        { id: "Saya mau nasi goreng, tidak pedas.", pl: "Poproszę nasi goreng, nieostre." },
        { id: "Saya sudah makan.", pl: "Już jadłem." },
        { id: "Minta air putih, tolong.", pl: "Poproszę wodę." },
      ],
    },
    vocab: [
      { id: "nasi goreng", pl: "smażony ryż" },
      { id: "mie", pl: "makaron" },
      { id: "ayam", pl: "kurczak" },
      { id: "ikan", pl: "ryba" },
      { id: "sayur", pl: "warzywa" },
      { id: "air putih", pl: "woda" },
      { id: "teh manis", pl: "słodka herbata" },
      { id: "pedas", pl: "ostry" },
      { id: "enak", pl: "smaczny" },
      { id: "bon", pl: "rachunek" },
    ],
    exercises: [
      { kind: "flashcard", id: "a1-v2-f1", front: "ayam", back: "kurczak" },
      { kind: "flashcard", id: "a1-v2-f2", front: "enak", back: "smaczny" },
      {
        kind: "match",
        id: "a1-v2-m1",
        pairs: [
          { id: "ikan", pl: "ryba" },
          { id: "sayur", pl: "warzywa" },
          { id: "air putih", pl: "woda" },
          { id: "pedas", pl: "ostry" },
        ],
      },
      {
        kind: "builder",
        id: "a1-v2-b1",
        words: ["Saya", "mau", "nasi", "goreng"],
        solution: "Saya mau nasi goreng",
        pl: "Poproszę nasi goreng.",
      },
      {
        kind: "choice",
        id: "a1-v2-c1",
        question: "Jak powiedzieć „to nie jest herbata”?",
        options: ["Ini bukan teh", "Ini tidak teh", "Ini teh tidak"],
        answer: "Ini bukan teh",
        explain: "Przed rzeczownikiem zawsze „bukan”.",
      },
    ],
  },
  {
    id: "a2-v1",
    level: "A2",
    kind: "vocab",
    title: "Części ciała",
    subtitle: "Ciało + przedrostek ber-",
    icon: "🫀",
    context: {
      key: "body",
      label: "Części ciała",
      brief: "opisywanie ciała i samopoczucia: sakit, berambut, bermata",
    },
    grammar: {
      title: "ber- z częściami ciała = „mieć/być z”",
      body: [
        "ber- + rzeczownik oznacza posiadanie cechy: rambut → berambut panjang (mieć długie włosy), kacamata → berkacamata (nosić okulary).",
        "„Sakit” + część ciała = boli mnie: „Kepala saya sakit.” (Boli mnie głowa.)",
        "Liczba mnoga przez reduplikację działa też tutaj: tangan-tangan (ręce, wiele osób).",
      ],
      examples: [
        { id: "Dia berambut panjang.", pl: "Ona ma długie włosy." },
        { id: "Perut saya sakit.", pl: "Boli mnie brzuch." },
      ],
    },
    vocab: [
      { id: "kepala", pl: "głowa" },
      { id: "mata", pl: "oko" },
      { id: "telinga", pl: "ucho" },
      { id: "hidung", pl: "nos" },
      { id: "mulut", pl: "usta" },
      { id: "tangan", pl: "ręka" },
      { id: "kaki", pl: "noga, stopa" },
      { id: "perut", pl: "brzuch" },
      { id: "rambut", pl: "włosy" },
    ],
    exercises: [
      { kind: "flashcard", id: "a2-v1-f1", front: "telinga", back: "ucho" },
      { kind: "flashcard", id: "a2-v1-f2", front: "perut", back: "brzuch" },
      {
        kind: "match",
        id: "a2-v1-m1",
        pairs: [
          { id: "kepala", pl: "głowa" },
          { id: "tangan", pl: "ręka" },
          { id: "kaki", pl: "noga, stopa" },
          { id: "hidung", pl: "nos" },
        ],
      },
      {
        kind: "blocks",
        id: "a2-v1-x1",
        prompt: "Zbuduj „mieć długie włosy” od „rambut”",
        root: "rambut",
        affixes: ["ber-", "me-", "di-", "ter-"],
        answer: "ber-",
        pl: "berambut panjang — mieć długie włosy",
      },
      {
        kind: "builder",
        id: "a2-v1-b1",
        words: ["Kepala", "saya", "sakit"],
        solution: "Kepala saya sakit",
        pl: "Boli mnie głowa.",
      },
    ],
  },
  {
    id: "a2-v2",
    level: "A2",
    kind: "vocab",
    title: "Podróże i transport",
    subtitle: "Pytania, klasyfikatory, lebih/paling",
    icon: "🛵",
    context: {
      key: "travel",
      label: "Podróże i transport",
      brief: "podróżowanie po Indonezji: taksówka, pociąg, bilety, pytanie o drogę",
    },
    grammar: {
      title: "Pytania w drodze",
      body: [
        "Słowa pytające: apa (co), siapa (kto), di mana (gdzie), ke mana (dokąd), kapan (kiedy), berapa (ile), bagaimana (jak).",
        "Porównania: „Kereta lebih cepat daripada bus.” (Pociąg jest szybszy niż autobus.) „paling murah” = najtańszy.",
        "Klasyfikatory: dua orang (dwie osoby), tiga buah tiket (trzy bilety).",
      ],
      examples: [
        { id: "Berapa harga tiket ke Bali?", pl: "Ile kosztuje bilet na Bali?" },
        { id: "Stasiun kereta di mana?", pl: "Gdzie jest dworzec kolejowy?" },
      ],
    },
    vocab: [
      { id: "kereta", pl: "pociąg" },
      { id: "pesawat", pl: "samolot" },
      { id: "bus", pl: "autobus" },
      { id: "ojek", pl: "taksówka motocyklowa" },
      { id: "tiket", pl: "bilet" },
      { id: "jalan", pl: "ulica, droga" },
      { id: "bandara", pl: "lotnisko" },
      { id: "stasiun", pl: "dworzec" },
      { id: "kanan", pl: "prawo" },
      { id: "kiri", pl: "lewo" },
    ],
    exercises: [
      { kind: "flashcard", id: "a2-v2-f1", front: "bandara", back: "lotnisko" },
      { kind: "flashcard", id: "a2-v2-f2", front: "ojek", back: "taksówka motocyklowa" },
      {
        kind: "match",
        id: "a2-v2-m1",
        pairs: [
          { id: "kereta", pl: "pociąg" },
          { id: "tiket", pl: "bilet" },
          { id: "kanan", pl: "prawo" },
          { id: "kiri", pl: "lewo" },
        ],
      },
      {
        kind: "builder",
        id: "a2-v2-b1",
        words: ["Berapa", "harga", "tiket", "ke", "Bali"],
        solution: "Berapa harga tiket ke Bali",
        pl: "Ile kosztuje bilet na Bali?",
      },
      {
        kind: "choice",
        id: "a2-v2-c1",
        question: "„Trzy bilety” to:",
        options: ["tiga buah tiket", "tiga ekor tiket", "tiga orang tiket"],
        answer: "tiga buah tiket",
        explain: "„buah” to klasyfikator przedmiotów; ekor dla zwierząt, orang dla ludzi.",
      },
    ],
  },
  {
    id: "b1-v1",
    level: "B1",
    kind: "vocab",
    title: "Zakupy i targowanie się",
    subtitle: "Ceny, -kan, tawar-menawar",
    icon: "🛍️",
    context: {
      key: "shopping",
      label: "Zakupy i targowanie się",
      brief: "targ w Indonezji: ceny, negocjacje, rozmiary, płatność",
    },
    grammar: {
      title: "Targowanie z sufiksem -kan",
      body: [
        "-kan czyni czasownik przechodnim/„dla kogoś”: „Murahkan sedikit, dong!” (Obniż trochę cenę!), „Tunjukkan yang lain.” (Pokaż inny.)",
        "Formy grzeczne: „Boleh kurang?” (Może być taniej?), „Terlalu mahal.” (Za drogo.)",
        "„-lah” łagodzi rozkaz: „Ambillah!” (Weź, proszę.)",
      ],
      examples: [
        { id: "Berapa harganya? Terlalu mahal!", pl: "Ile to kosztuje? Za drogo!" },
        { id: "Boleh kurang sedikit?", pl: "Może być trochę taniej?" },
      ],
    },
    vocab: [
      { id: "harga", pl: "cena" },
      { id: "mahal", pl: "drogi" },
      { id: "murah", pl: "tani" },
      { id: "pasar", pl: "targ" },
      { id: "toko", pl: "sklep" },
      { id: "uang", pl: "pieniądze" },
      { id: "diskon", pl: "zniżka" },
      { id: "membeli", pl: "kupować" },
      { id: "menawar", pl: "targować się" },
    ],
    exercises: [
      { kind: "flashcard", id: "b1-v1-f1", front: "menawar", back: "targować się" },
      { kind: "flashcard", id: "b1-v1-f2", front: "murah", back: "tani" },
      {
        kind: "match",
        id: "b1-v1-m1",
        pairs: [
          { id: "harga", pl: "cena" },
          { id: "pasar", pl: "targ" },
          { id: "uang", pl: "pieniądze" },
          { id: "mahal", pl: "drogi" },
        ],
      },
      {
        kind: "blocks",
        id: "b1-v1-x1",
        prompt: "Zbuduj „obniż (cenę)” od rdzenia „murah”",
        root: "murah",
        affixes: ["-kan", "-i", "ber-", "ke-...-an"],
        answer: "-kan",
        pl: "murahkan — obniż cenę",
      },
      {
        kind: "builder",
        id: "b1-v1-b1",
        words: ["Boleh", "kurang", "sedikit"],
        solution: "Boleh kurang sedikit",
        pl: "Może być trochę taniej?",
      },
    ],
  },
  {
    id: "b1-v2",
    level: "B1",
    kind: "vocab",
    title: "Kultura i savoir-vivre",
    subtitle: "Grzeczność, strona bierna di-",
    icon: "🙏",
    context: {
      key: "culture",
      label: "Kultura i savoir-vivre",
      brief: "zasady kultury indonezyjskiej: grzeczność, gesty, zaproszenia, religia",
    },
    grammar: {
      title: "Bierność i dystans = grzeczność",
      body: [
        "Indonezyjczycy chętnie używają strony biernej di-, by nie wskazywać palcem sprawcy: „Sepatu harus dilepas.” (Buty trzeba zdjąć.)",
        "Zwroty adresatywne: Pak (do mężczyzny), Bu (do kobiety), Mas/Mbak (młodsza osoba na Jawie).",
        "Nigdy nie podawaj i nie przyjmuj lewą ręką — „dengan tangan kanan” (prawą ręką).",
      ],
      examples: [
        { id: "Sepatu dilepas sebelum masuk.", pl: "Buty zdejmuje się przed wejściem." },
        { id: "Permisi, Pak.", pl: "Przepraszam, proszę pana." },
      ],
    },
    vocab: [
      { id: "sopan", pl: "grzeczny" },
      { id: "adat", pl: "zwyczaj, tradycja" },
      { id: "tamu", pl: "gość" },
      { id: "undangan", pl: "zaproszenie" },
      { id: "masjid", pl: "meczet" },
      { id: "permisi", pl: "przepraszam (przechodząc)" },
      { id: "menghormati", pl: "szanować" },
      { id: "salam", pl: "pozdrowienie" },
    ],
    exercises: [
      { kind: "flashcard", id: "b1-v2-f1", front: "adat", back: "zwyczaj, tradycja" },
      { kind: "flashcard", id: "b1-v2-f2", front: "tamu", back: "gość" },
      {
        kind: "match",
        id: "b1-v2-m1",
        pairs: [
          { id: "sopan", pl: "grzeczny" },
          { id: "undangan", pl: "zaproszenie" },
          { id: "permisi", pl: "przepraszam (przechodząc)" },
          { id: "menghormati", pl: "szanować" },
        ],
      },
      {
        kind: "blocks",
        id: "b1-v2-x1",
        prompt: "Zbuduj stronę bierną „jest zdejmowane” od „lepas”",
        root: "lepas",
        affixes: ["di-", "me-", "ber-", "per-...-an"],
        answer: "di-",
        pl: "dilepas — jest zdejmowane",
      },
      {
        kind: "choice",
        id: "b1-v2-c1",
        question: "Jak grzecznie zwrócić się do starszego mężczyzny?",
        options: ["Pak", "Mbak", "Bung"],
        answer: "Pak",
        explain: "Pak (bapak) to standardowy grzecznościowy zwrot do mężczyzny.",
      },
    ],
  },
  {
    id: "b1-v3",
    level: "B1",
    kind: "vocab",
    title: "Zakwaterowanie i hotel",
    subtitle: "Rezerwacje, prośby, ter-",
    icon: "🏨",
    context: {
      key: "accommodation",
      label: "Zakwaterowanie i hotel",
      brief: "hotel i homestay: rezerwacja, pokój, problemy, meldunek",
    },
    grammar: {
      title: "ter- = stan mimowolny",
      body: [
        "ter- opisuje stan lub przypadkowość: „Pintunya terkunci.” (Drzwi są zamknięte na klucz.), „Saya tertidur.” (Zasnąłem niechcący.)",
        "Prośby w hotelu: „Bisa minta handuk lagi?” (Mogę prosić o kolejny ręcznik?)",
        "Spójniki: karena (bo), tetapi (ale), jadi (więc) — do tłumaczenia problemów.",
      ],
      examples: [
        { id: "AC di kamar saya tidak berfungsi.", pl: "Klimatyzacja w moim pokoju nie działa." },
        { id: "Saya sudah memesan kamar untuk dua malam.", pl: "Zarezerwowałem pokój na dwie noce." },
      ],
    },
    vocab: [
      { id: "kamar", pl: "pokój" },
      { id: "kunci", pl: "klucz" },
      { id: "handuk", pl: "ręcznik" },
      { id: "penginapan", pl: "nocleg" },
      { id: "memesan", pl: "rezerwować" },
      { id: "malam", pl: "noc" },
      { id: "sarapan", pl: "śniadanie" },
      { id: "kasur", pl: "łóżko" },
    ],
    exercises: [
      { kind: "flashcard", id: "b1-v3-f1", front: "handuk", back: "ręcznik" },
      { kind: "flashcard", id: "b1-v3-f2", front: "sarapan", back: "śniadanie" },
      {
        kind: "match",
        id: "b1-v3-m1",
        pairs: [
          { id: "kamar", pl: "pokój" },
          { id: "kunci", pl: "klucz" },
          { id: "memesan", pl: "rezerwować" },
          { id: "penginapan", pl: "nocleg" },
        ],
      },
      {
        kind: "blocks",
        id: "b1-v3-x1",
        prompt: "Zbuduj „zamknięty na klucz” od „kunci”",
        root: "kunci",
        affixes: ["ter-", "ber-", "-kan", "ke-...-an"],
        answer: "ter-",
        pl: "terkunci — zamknięty na klucz",
      },
      {
        kind: "builder",
        id: "b1-v3-b1",
        words: ["Saya", "mau", "kamar", "untuk", "dua", "malam"],
        solution: "Saya mau kamar untuk dua malam",
        pl: "Chcę pokój na dwie noce.",
      },
    ],
  },
  {
    id: "b2-v1",
    level: "B2",
    kind: "vocab",
    title: "Zdrowie i apteka",
    subtitle: "Objawy, ke-an, prośby",
    icon: "💊",
    context: {
      key: "health",
      label: "Zdrowie i apteka",
      brief: "wizyta u lekarza i w aptece: objawy, leki, samopoczucie",
    },
    grammar: {
      title: "ke- -an dla dolegliwości",
      body: [
        "ke- -an często opisuje coś, co nas spotkało: kedinginan (zmarznąć), kepanasan (przegrzać się), kelelahan (przemęczenie), keracunan (zatrucie).",
        "„Saya merasa…” (czuję się…) + przymiotnik: pusing (zawroty), mual (mdłości), lemas (osłabiony).",
        "W aptece: „Ada obat untuk…?” (Czy jest lek na…?)",
      ],
      examples: [
        { id: "Saya keracunan makanan kemarin.", pl: "Wczoraj zatrułem się jedzeniem." },
        { id: "Ada obat untuk sakit kepala?", pl: "Czy jest lek na ból głowy?" },
      ],
    },
    vocab: [
      { id: "obat", pl: "lek" },
      { id: "apotek", pl: "apteka" },
      { id: "dokter", pl: "lekarz" },
      { id: "demam", pl: "gorączka" },
      { id: "batuk", pl: "kaszel" },
      { id: "pusing", pl: "zawroty głowy" },
      { id: "mual", pl: "mdłości" },
      { id: "rumah sakit", pl: "szpital" },
      { id: "keracunan", pl: "zatrucie" },
    ],
    exercises: [
      { kind: "flashcard", id: "b2-v1-f1", front: "demam", back: "gorączka" },
      { kind: "flashcard", id: "b2-v1-f2", front: "apotek", back: "apteka" },
      {
        kind: "match",
        id: "b2-v1-m1",
        pairs: [
          { id: "obat", pl: "lek" },
          { id: "dokter", pl: "lekarz" },
          { id: "batuk", pl: "kaszel" },
          { id: "rumah sakit", pl: "szpital" },
        ],
      },
      {
        kind: "blocks",
        id: "b2-v1-x1",
        prompt: "Zbuduj „zmarznąć” od „dingin”",
        root: "dingin",
        affixes: ["ke-...-an", "per-...-an", "me-", "-i"],
        answer: "ke-...-an",
        pl: "kedinginan — zmarznąć",
      },
      {
        kind: "builder",
        id: "b2-v1-b1",
        words: ["Ada", "obat", "untuk", "sakit", "kepala"],
        solution: "Ada obat untuk sakit kepala",
        pl: "Czy jest lek na ból głowy?",
      },
    ],
  },
  {
    id: "b2-v2",
    level: "B2",
    kind: "vocab",
    title: "Pogoda i klimat",
    subtitle: "Pory roku, reduplikacje",
    icon: "🌧️",
    context: {
      key: "weather",
      label: "Pogoda i klimat",
      brief: "rozmowa o pogodzie i porach roku w tropikach",
    },
    grammar: {
      title: "Pogoda, reduplikacje i ke-an",
      body: [
        "Dwie pory roku: musim hujan (pora deszczowa), musim kemarau (pora sucha).",
        "kehujanan = zostać złapanym przez deszcz; kepanasan = cierpieć od upału.",
        "Reduplikacja przysłówkowa: „kadang-kadang” (czasami), „tiba-tiba” (nagle) — sens inny niż liczba mnoga.",
      ],
      examples: [
        { id: "Tiba-tiba hujan deras sekali.", pl: "Nagle spadł bardzo ulewny deszcz." },
        { id: "Saya kehujanan di jalan.", pl: "Złapał mnie deszcz na ulicy." },
      ],
    },
    vocab: [
      { id: "hujan", pl: "deszcz" },
      { id: "panas", pl: "gorąco" },
      { id: "dingin", pl: "zimno" },
      { id: "angin", pl: "wiatr" },
      { id: "awan", pl: "chmura" },
      { id: "petir", pl: "piorun" },
      { id: "musim kemarau", pl: "pora sucha" },
      { id: "kadang-kadang", pl: "czasami" },
    ],
    exercises: [
      { kind: "flashcard", id: "b2-v2-f1", front: "petir", back: "piorun" },
      { kind: "flashcard", id: "b2-v2-f2", front: "kadang-kadang", back: "czasami" },
      {
        kind: "match",
        id: "b2-v2-m1",
        pairs: [
          { id: "hujan", pl: "deszcz" },
          { id: "angin", pl: "wiatr" },
          { id: "awan", pl: "chmura" },
          { id: "musim kemarau", pl: "pora sucha" },
        ],
      },
      {
        kind: "choice",
        id: "b2-v2-c1",
        question: "„tiba-tiba” znaczy:",
        options: ["nagle", "przybycia", "powoli"],
        answer: "nagle",
        explain: "Reduplikacja zmienia znaczenie: tiba (przybyć) → tiba-tiba (nagle).",
      },
      {
        kind: "blocks",
        id: "b2-v2-x1",
        prompt: "Zbuduj „zostać złapanym przez deszcz” od „hujan”",
        root: "hujan",
        affixes: ["ke-...-an", "ber-", "di-", "-lah"],
        answer: "ke-...-an",
        pl: "kehujanan — zostać złapanym przez deszcz",
      },
    ],
  },
  {
    id: "b2-v3",
    level: "B2",
    kind: "vocab",
    title: "Praca i biznes",
    subtitle: "Bahasa baku w biurze",
    icon: "💼",
    context: {
      key: "work",
      label: "Praca i biznes",
      brief: "rozmowa biznesowa i o pracy w formalnym bahasa baku",
    },
    grammar: {
      title: "per- -an i język formalny",
      body: [
        "per- -an tworzy nazwy instytucji i procesów: usaha → perusahaan (firma), dagang → perdagangan (handel), janji → perjanjian (umowa).",
        "W biurze używaj baku: saya (nie gue), tidak (nie nggak), bagaimana (nie gimana).",
        "Zwroty: „Mohon maaf atas keterlambatan.” (Przepraszam za spóźnienie.)",
      ],
      examples: [
        { id: "Saya bekerja di perusahaan teknologi.", pl: "Pracuję w firmie technologicznej." },
        { id: "Mari kita bahas perjanjian ini.", pl: "Omówmy tę umowę." },
      ],
    },
    vocab: [
      { id: "pekerjaan", pl: "praca, zawód" },
      { id: "perusahaan", pl: "firma" },
      { id: "rapat", pl: "spotkanie, zebranie" },
      { id: "gaji", pl: "pensja" },
      { id: "perjanjian", pl: "umowa" },
      { id: "atasan", pl: "przełożony" },
      { id: "karyawan", pl: "pracownik" },
      { id: "perdagangan", pl: "handel" },
    ],
    exercises: [
      { kind: "flashcard", id: "b2-v3-f1", front: "rapat", back: "spotkanie, zebranie" },
      { kind: "flashcard", id: "b2-v3-f2", front: "gaji", back: "pensja" },
      {
        kind: "match",
        id: "b2-v3-m1",
        pairs: [
          { id: "pekerjaan", pl: "praca, zawód" },
          { id: "karyawan", pl: "pracownik" },
          { id: "atasan", pl: "przełożony" },
          { id: "perjanjian", pl: "umowa" },
        ],
      },
      {
        kind: "blocks",
        id: "b2-v3-x1",
        prompt: "Zbuduj „handel” od rdzenia „dagang”",
        root: "dagang",
        affixes: ["per-...-an", "ke-...-an", "ter-", "-kan"],
        answer: "per-...-an",
        pl: "perdagangan — handel",
      },
      {
        kind: "choice",
        id: "b2-v3-c1",
        question: "Formalnie (baku) powiesz do szefa:",
        options: [
          "Bagaimana pendapat Bapak?",
          "Gimana nih, bos?",
          "Gue mau tanya, napa?",
        ],
        answer: "Bagaimana pendapat Bapak?",
        explain: "W biurze obowiązuje bahasa baku, nie gaul.",
      },
    ],
  },
];
