/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PowtorkiRouteImport } from './routes/powtorki'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PrzygodaRouteImport } from './routes/przygoda'
import { Route as RozmowaRouteImport } from './routes/rozmowa'
import { Route as LekcjaIdRouteImport } from './routes/lekcja.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PowtorkiRoute = PowtorkiRouteImport.update({
  id: '/powtorki',
  path: '/powtorki',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrzygodaRoute = PrzygodaRouteImport.update({
  id: '/przygoda',
  path: '/przygoda',
  getParentRoute: () => rootRouteImport,
} as any)
const RozmowaRoute = RozmowaRouteImport.update({
  id: '/rozmowa',
  path: '/rozmowa',
  getParentRoute: () => rootRouteImport,
} as any)
const LekcjaIdRoute = LekcjaIdRouteImport.update({
  id: '/lekcja/$id',
  path: '/lekcja/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/powtorki': typeof PowtorkiRoute
  '/profil': typeof ProfilRoute
  '/przygoda': typeof PrzygodaRoute
  '/rozmowa': typeof RozmowaRoute
  '/lekcja/$id': typeof LekcjaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/powtorki': typeof PowtorkiRoute
  '/profil': typeof ProfilRoute
  '/przygoda': typeof PrzygodaRoute
  '/rozmowa': typeof RozmowaRoute
  '/lekcja/$id': typeof LekcjaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/powtorki': typeof PowtorkiRoute
  '/profil': typeof ProfilRoute
  '/przygoda': typeof PrzygodaRoute
  '/rozmowa': typeof RozmowaRoute
  '/lekcja/$id': typeof LekcjaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/powtorki'
    | '/profil'
    | '/przygoda'
    | '/rozmowa'
    | '/lekcja/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/powtorki'
    | '/profil'
    | '/przygoda'
    | '/rozmowa'
    | '/lekcja/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/powtorki'
    | '/profil'
    | '/przygoda'
    | '/rozmowa'
    | '/lekcja/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PowtorkiRoute: typeof PowtorkiRoute
  ProfilRoute: typeof ProfilRoute
  PrzygodaRoute: typeof PrzygodaRoute
  RozmowaRoute: typeof RozmowaRoute
  LekcjaIdRoute: typeof LekcjaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powtorki': {
      id: '/powtorki'
      path: '/powtorki'
      fullPath: '/powtorki'
      preLoaderRoute: typeof PowtorkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/przygoda': {
      id: '/przygoda'
      path: '/przygoda'
      fullPath: '/przygoda'
      preLoaderRoute: typeof PrzygodaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rozmowa': {
      id: '/rozmowa'
      path: '/rozmowa'
      fullPath: '/rozmowa'
      preLoaderRoute: typeof RozmowaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lekcja/$id': {
      id: '/lekcja/$id'
      path: '/lekcja/$id'
      fullPath: '/lekcja/$id'
      preLoaderRoute: typeof LekcjaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PowtorkiRoute: PowtorkiRoute,
  ProfilRoute: ProfilRoute,
  PrzygodaRoute: PrzygodaRoute,
  RozmowaRoute: RozmowaRoute,
  LekcjaIdRoute: LekcjaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
